name: carecompanion_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter


  flutter_tts: ^3.6.2  
  speech_to_text: ^7.3.0   
  path_provider: ^2.0.15
  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.0
  cloud_firestore: ^4.9.0
  workmanager: ^0.5.0
  flutter_lints: ^6.0.0
  file_picker: ^5.2.5
  uuid: ^3.0.6
  http: ^0.13.6
  

flutter:
  uses-material-design: true


  assets:
    - assets\data\dummy_data.json
